trigger: none
# uncomment this for auto trigger
#  branches:
#    include:
#      - releases/*
#    exclude:
#      - main
#pr: none

variables:
- group: image-sync
- name: templateFile
  value: '$(Build.SourcesDirectory)/pipeline/image-sync/images.txt'
- name: azureSubscription
  value: 'az-pulumi'
- name: acrName
  value: 'devaksacreb86a9ea'

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'import images to ACR $(azureSubscription)'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'pipeline/image-sync/sync-script.sh'
    arguments: '$(acrName) $(templateFile) $(DOCKER_NAME) $(DOCKER_PASS)'
    useGlobalConfig: true
    keepAzSessionActive: true
