parameters:
- name: stack
  type: string
- name: workDir
  type: string
- name: azureSubscription
  type: string

jobs:
- job: "build_and_deploy"
  displayName: Build & Deploy
  steps:
  - template: build-template.yml
    parameters:
      stack: ${{ parameters.stack }}
      workDir: ${{ parameters.workDir }}

  - template: deploy-template.yml
    parameters:
      stack: ${{ parameters.stack }}
      workDir: ${{ parameters.workDir }}
      azureSubscription: ${{ parameters.azureSubscription }}
