{{- if .Values.letsencrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: '{{ .Release.Namespace }}'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: '{{ .Values.letsencrypt.email }}'
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: '{{ .Values.letsencrypt.email }}'
          apiTokenSecretRef:
            name: cf-dns-secret
            key: token
{{- end }}