{{- if .Values.letsencrypt.enabled }}
apiVersion: "v1"
kind: Secret
metadata:
  name: cf-dns-secret
  namespace: '{{ .Release.Namespace }}'
stringData:
  token: '{{ .Values.letsencrypt.cfToken }}'
{{- end }}