parameters:
- name: stack
  type: string
- name: workDir
  type: string
- name: forceInstall
  type: string
  default: false
- name: azureSubscription
  type: string
- name: npm_config_cache
  type: string
  default: $(Pipeline.Workspace)/.npm
- name: buildPulumi
  type: string
  default: false

jobs:
- job: "build_deploy"
  displayName: Build & Deploy
  steps:
  - template: build-template.yml
    parameters:
      stack: ${{ parameters.stack }}
      workDir: ${{ parameters.workDir }}
      azureSubscription: ${{ parameters.azureSubscription }}
      npm_config_cache: ${{ parameters.npm_config_cache }}
      buildPulumi: ${{ parameters.buildPulumi }}

  - template: deploy-template.yml
    parameters:
      stack: ${{ parameters.stack }}
      workDir: ${{ parameters.workDir }}
      azureSubscription: ${{ parameters.azureSubscription }}
