{{- if .Values.network.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: '{{ include "app.fullname" . }}-network-policy'
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress: []
  egress:
    - to:
        - {{- range $cidr := .Values.network.cidrs }}
          ipBlock:
            cidr: {{ $cidr }}
          {{- end }}
      ports:
        {{- range $p := .Values.network.ports }}
        - port: {{ $p }}
          protocol: TCP
        {{- end }}
{{- end }}