apiVersion: v2
name: nginx-ingress
description: The template to deploy an nginx and cert manager to Kubernetes
type: application
version: 1.0.0
appVersion: 'latest'

dependencies:
  - name: ingress-nginx
    alias: nginx
    version: 4.x.x
    condition: nginx.enabled
    repository: "https://kubernetes.github.io/ingress-nginx"

  - name: cert-manager
    alias: certmanager
    version: 1.x.x
    condition: certmanager.enabled
    repository: "https://charts.jetstack.io"