#====================cf-tunnel=======================
cf-tunnel:
  enabled: true
  global:
    image: '${{acrName}}.azurecr.io/cloudflare/cloudflared'
    tag: 'latest'
  deployment:
    enabled: true
    replicaCount: 2
    args:
      - tunnel
      - '--no-autoupdate'
      - run
      - '--token'
      - $(token)
  secrets:
    token: '${{cf-tunnel-token}}'
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  podSecurityContext:
    fsGroup: 10000
    runAsUser: 10000
    runAsGroup: 10000
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true

#====================enable network rule=======================
network:
  enabled: true
  cidrs:
  - '192.168.31.250/32'
  - '192.168.32.128/27'
  ports:
    - 443
    - 80
    - 22